#line 1 "flex_bison/src/haskell.flex.cpp"

#line 3 "flex_bison/src/haskell.flex.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer yyFlexLexer

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */
#include <iostream>
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	std::streambuf* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>

int yyFlexLexer::yywrap() { return 1; }

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 95
#define YY_END_OF_BUFFER 96
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[225] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       96,   95,   94,   95,   90,   59,   57,   95,   77,   23,
       24,   32,   30,   31,   51,   33,   67,   67,   48,   29,
       41,   47,   42,   61,   65,   27,   56,   28,   58,    1,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   25,   54,   26,   62,   92,   93,   86,
       88,   89,   86,   71,   72,   74,   95,   55,   45,   49,
       70,   52,   50,   40,    0,   67,    0,    0,    0,   67,
       67,   60,   53,   43,   39,   63,   44,   65,   67,    0,
       64,   64,   64,   64,   64,   64,   11,   64,   64,   12,

       64,   64,   64,   64,   64,   64,    7,   64,   64,   64,
       64,   73,   46,    0,   87,   85,   85,   91,    0,   78,
       79,   80,   81,   82,   84,   83,   74,   75,   76,   69,
        0,    0,   69,    0,   66,    0,   68,    0,   64,   64,
       64,   64,   64,   34,   64,   64,   64,   64,   64,   15,
       35,   64,   64,   37,   64,   64,   64,   38,    0,    0,
       85,   85,    0,   69,    0,   69,   66,   68,    2,   64,
        4,   64,   64,   13,   64,   64,   64,   64,   64,   64,
       64,    8,    6,   64,   85,    0,   85,    0,    0,   69,
        0,    3,   64,   64,   64,   64,   17,   64,   64,   64,

       64,   14,   85,   85,    0,   69,   64,   64,   64,   21,
       18,   19,   64,   22,   36,   64,    9,   64,   16,   64,
        5,   10,   20,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    6,    7,    8,    9,   10,
       11,   12,   13,    1,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   19,   19,   20,   21,   22,
       23,   24,    1,   25,   26,   26,   26,   26,   27,   26,
       28,   28,   28,   28,   28,   28,   28,   28,   29,   28,
       28,   28,   28,   28,   28,   28,   28,   30,   28,   28,
       31,   32,   33,   34,   35,    1,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   45,   45,   46,   47,   48,
       49,   50,   45,   51,   52,   53,   54,   55,   56,   57,
       58,   45,   59,   60,   61,   62,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[63] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    1,
        1,    1,    1,    3,    1,    1,    4,    4,    4,    1,
        1,    1,    1,    1,    1,    4,    4,    2,    2,    2,
        1,    1,    1,    1,    4,    4,    4,    4,    4,    4,
        4,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    1,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[235] =
    {   0,
        0,    0,   58,   59,   56,   57,  402,  401,  389,  388,
      401,  406,  406,  396,  406,  406,  406,  391,  406,  406,
      406,  406,  385,   53,  382,  373,   77,   83,  375,  406,
       55,   47,  371,  406,    0,  406,  406,  406,  406,   62,
        0,   36,   75,  347,  343,   27,  351,  341,   36,  348,
       41,  345,  338,  372,  325,  406,  406,  406,  406,  133,
      406,  406,   91,  406,  406,    0,  323,  406,  406,  406,
      406,  406,  406,  406,  103,  140,  159,   96,  348,    0,
      172,  406,  406,  406,  406,  406,  406,    0,    0,  144,
        0,  330,  345,  327,   32,  324,    0,  326,  326,    0,

      326,   64,  322,  330,   87,  312,    0,  322,  293,  302,
      290,  406,  406,  151,  406,  179,  183,  406,  186,  406,
      406,  406,  406,  406,  406,  406,    0,  406,  406,  198,
      205,  212,  224,  231,  131,  175,  304,  303,  296,  283,
      297,  296,  287,    0,  290,  289,  266,  266,  248,    0,
      245,  254,  220,    0,  220,  227,  214,    0,  202,  227,
      234,  237,  257,  260,  263,  267,  271,  226,    0,  208,
        0,  204,  202,    0,  202,  188,  178,  198,  186,  174,
      168,    0,    0,  173,  276,  279,  176,  171,  286,  290,
      299,    0,  149,  141,  140,  118,   57,  116,  120,  116,

       97,    0,  302,  110,  305,  309,   87,   89,   85,    0,
        0,    0,   92,    0,    0,   85,    0,   67,    0,   53,
        0,    0,    0,  406,  344,  348,  352,  356,  359,  362,
      366,  370,   83,   82
    } ;

static const flex_int16_t yy_def[235] =
    {   0,
      224,    1,  225,  225,  226,  226,  227,  227,  228,  228,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  229,  224,  224,  224,  224,  224,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  231,  232,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  233,   27,
      224,  224,  224,  224,  224,  224,  224,  229,   27,  224,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,

      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  231,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  233,  233,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  224,  234,
      224,  224,  224,  224,  224,  224,  224,  233,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  224,  224,  234,  234,  224,  224,
      224,  230,  230,  230,  230,  230,  230,  230,  230,  230,

      230,  230,  224,  234,  224,  224,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,    0,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224
    } ;

static const flex_int16_t yy_nxt[469] =
    {   0,
       12,   13,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   28,   29,
       30,   31,   32,   33,   34,   35,   35,   35,   35,   35,
       36,   37,   38,   39,   40,   41,   41,   42,   43,   44,
       45,   41,   41,   46,   41,   47,   48,   49,   50,   41,
       41,   41,   51,   41,   41,   52,   53,   41,   54,   55,
       56,   57,   59,   59,   62,   62,   71,  100,   83,   85,
       86,   92,  142,  101,  102,  105,   72,   84,   89,   76,
       76,   93,  143,  108,  106,  187,  137,   63,   63,   60,
       60,   75,  223,   76,   76,   76,   90,   75,  109,   76,

       76,   76,  211,   77,  148,   78,   79,  212,  222,   77,
       94,   80,  135,  135,   95,  149,   77,   81,   96,  130,
      130,  130,   77,   97,  221,   78,  120,  121,  152,  220,
      136,  122,  219,   79,  114,  114,  218,  131,  123,  217,
      115,  124,  153,  125,  204,  126,  216,  135,  135,  116,
      117,  117,  114,  114,   75,  215,   76,   76,   76,  214,
       89,   76,   76,  213,  118,  167,   77,  119,  120,  121,
      210,  132,  132,  122,   81,  133,  133,  133,   90,   77,
      123,  209,  118,  124,  208,  125,   75,  126,   76,   76,
       76,  135,  135,  134,  207,  117,  117,  117,   77,  117,

      117,  117,  116,  117,  117,  188,   81,  159,  160,  136,
      204,   77,  202,  161,  130,  130,  130,  162,  185,  185,
      119,  130,  130,  130,  163,  201,  200,  159,  133,  133,
      133,  199,  164,  198,  197,  160,  186,  163,  196,  131,
      133,  133,  133,  132,  132,  195,  165,  133,  133,  133,
      117,  117,  117,  117,  117,  117,  194,  193,  166,  192,
      168,  188,  159,  160,  184,  134,  183,  182,  161,  189,
      189,  162,  181,  190,  190,  190,  130,  130,  130,  133,
      133,  133,  159,  133,  133,  133,  163,  135,  135,  180,
      160,  191,  185,  185,  164,  185,  185,  165,  179,  163,

      178,  166,  190,  190,  190,  167,  190,  190,  190,  177,
      203,  189,  189,  186,  176,  190,  190,  190,  185,  185,
      205,  190,  190,  190,  206,  190,  190,  190,  175,  174,
      173,  172,  171,  191,  170,  169,  203,  138,  168,  205,
      158,  157,  156,  206,   58,   58,   58,   58,   61,   61,
       61,   61,   64,   64,   64,   64,   66,   66,   66,   66,
       88,  155,   88,   91,  154,   91,  127,  127,  151,  127,
      128,  128,  128,  128,  150,  147,  146,  145,  144,  141,
      140,  139,  138,  129,  113,  112,  111,  110,  107,  104,
      103,   99,   98,   87,   82,   74,   73,   70,   69,   68,

      224,   67,   67,   65,   65,   11,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224
    } ;

static const flex_int16_t yy_chk[469] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    6,   24,   46,   31,   32,
       32,   42,   95,   46,   46,   49,   24,   31,   40,   40,
       40,   42,   95,   51,   49,  234,  233,    5,    6,    3,
        4,   27,  220,   27,   27,   27,   40,   28,   51,   28,

       28,   28,  197,   27,  102,   27,   27,  197,  218,   28,
       43,   27,   78,   78,   43,  102,   27,   28,   43,   75,
       75,   75,   28,   43,  216,   27,   63,   63,  105,  213,
       78,   63,  209,   27,   60,   60,  208,   75,   63,  207,
       60,   63,  105,   63,  204,   63,  201,  135,  135,   60,
       60,   60,  114,  114,   76,  200,   76,   76,   76,  199,
       90,   90,   90,  198,   60,  135,   76,   60,   60,   60,
      196,   77,   77,   60,   76,   77,   77,   77,   90,   76,
       60,  195,  114,   60,  194,   60,   81,   60,   81,   81,
       81,  136,  136,   77,  193,  116,  116,  116,   81,  117,

      117,  117,  119,  119,  119,  188,   81,  116,  116,  136,
      187,   81,  184,  116,  130,  130,  130,  117,  159,  159,
      119,  131,  131,  131,  130,  181,  180,  116,  132,  132,
      132,  179,  130,  178,  177,  116,  159,  130,  176,  131,
      133,  133,  133,  134,  134,  175,  132,  134,  134,  134,
      161,  161,  161,  162,  162,  162,  173,  172,  133,  170,
      168,  160,  161,  161,  157,  134,  156,  155,  161,  163,
      163,  162,  153,  163,  163,  163,  164,  164,  164,  165,
      165,  165,  161,  166,  166,  166,  164,  167,  167,  152,
      161,  163,  185,  185,  164,  186,  186,  165,  151,  164,

      149,  166,  189,  189,  189,  167,  190,  190,  190,  148,
      185,  191,  191,  186,  147,  191,  191,  191,  203,  203,
      189,  205,  205,  205,  190,  206,  206,  206,  146,  145,
      143,  142,  141,  191,  140,  139,  203,  138,  137,  205,
      111,  110,  109,  206,  225,  225,  225,  225,  226,  226,
      226,  226,  227,  227,  227,  227,  228,  228,  228,  228,
      229,  108,  229,  230,  106,  230,  231,  231,  104,  231,
      232,  232,  232,  232,  103,  101,   99,   98,   96,   94,
       93,   92,   79,   67,   55,   54,   53,   52,   50,   48,
       47,   45,   44,   33,   29,   26,   25,   23,   18,   14,

       11,   10,    9,    8,    7,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      224,  224,  224,  224,  224,  224,  224,  224
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "flex_bison/resources/haskell.flex"
#line 5 "flex_bison/resources/haskell.flex"
	#include <string>
	#include <cstring>
	#include <memory>
	#include <algorithm>

	#include "FlexUtils.h"
	#include "BisonUtils.h"

	#ifdef DEBUG_LEXEMS
		 #define LOG_LEXEM(msg, ...) printf(msg, ##__VA_ARGS__);
	#else
		#define LOG_LEXEM(msg, ...)
	#endif

	#define UNPUT_STR(str) \
		for (auto it = str.end(); it >= str.begin(); it--) { \
			unput(*it); \
		}

	#define LOOKAHEAD(res) \
		res = ""; \
		char next_char; \
		do { \
			next_char = yyinput(); \
			if (next_char == EOF || next_char == '\0') { \
				unput(next_char); \
			} else { \
				res += next_char; \
			} \
		} while (next_char != EOF && next_char != '\0' || std::isalpha(next_char));

	#define EMIT_LEXEM \
	{ \
		switch(layoutBuilder->emitLexem()) { \
			case Lexem::OPEN_BRACE: \
				layoutBuilder->addLexem("{"); \
				printf("{\n"); \
				break; \
			case Lexem::CLOSING_BRACE: \
				layoutBuilder->addLexem("}"); \
				printf("}\n"); \
				break; \
			case Lexem::SEMICOLON: \
				layoutBuilder->addLexem(";"); \
				printf(";\n"); \
				break; \
			case Lexem::NONE: \
				break; \
		} \
    }

	#define YY_USER_ACTION EMIT_LEXEM

	static bool check_prefix(const std::string& input_string, int base);
	static int clean_integer(const std::string& input_string, std::string& cleaned, int base);
	std::string replaceComma(const std::string& str);
	unsigned occurencesCount(std::string str, std::string substr);

	int var;
	long double var_float;
	unsigned lineno = 1;
	unsigned opened_line;
	std::string buffer;

	std::unique_ptr<LayoutBuilder> layoutBuilder = std::make_unique<LayoutBuilder>();
#line 642 "flex_bison/src/haskell.flex.cpp"

#line 644 "flex_bison/src/haskell.flex.cpp"

#define INITIAL 0
#define STRING 1
#define CHAR 2
#define SINGLE_LINE_COMMENT 3
#define MULTI_LINE_COMMENT 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
\
	if ( (int)(result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
#define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin.rdbuf(std::cin.rdbuf());

		if ( ! yyout )
			yyout.rdbuf(std::cout.rdbuf());

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 92 "flex_bison/resources/haskell.flex"


#line 95 "flex_bison/resources/haskell.flex"
	// Если вставить сюда локальные переменные, то они будут пересоздаваться каждый раз при вызове yylex
	// Поэтому вынес отсюда всё что можно во избежание потери значений переменных между вызовами yylex


#line 788 "flex_bison/src/haskell.flex.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 225 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 406 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 99 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found lexem: _\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 100 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found lexem: case\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 101 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found lexem: class\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 102 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found lexem: data\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 103 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found lexem: newtype\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 104 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found lexem: type\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 105 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found lexem: of\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 106 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found lexem: then\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 107 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found lexem: default\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 108 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found lexem: deriving\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 109 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found lexem: do\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 110 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found lexem: if\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 111 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found lexem: else\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 112 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found lexem: where\n"); layoutBuilder->addLexem(std::string(yytext)); return WHEREKW; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 113 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found lexem: let\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 114 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found lexem: foreign\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 115 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found lexem: infix\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 116 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found lexem: infixl\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 117 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found lexem: infixr\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 118 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found lexem: instance\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 119 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found lexem: import\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 120 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found lexem: module\n"); layoutBuilder->addLexem(std::string(yytext)); return MODULEKW; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 122 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found opening parenthesis\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 123 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found closing parenthesis\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 124 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found opening curly brace\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 125 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found closing curly brace\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 126 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found opening square bracket\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 127 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found closing square bracket\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 128 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found semicolon\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 130 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operator: +\n"); layoutBuilder->addLexem(std::string(yytext)); return '+';}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 131 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operator: -\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 132 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operator: *\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 133 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operator: /\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 134 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operation: div\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 135 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operation: mod\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 136 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operation: negate\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 137 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operation: not\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 138 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operation: xor\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 139 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operator: ==\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 140 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operator: /=\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 141 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operator: <\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 142 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operator: >\n");layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 143 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operator: <=\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 144 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operator: >=\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 145 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operator: &&\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 146 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operator: ||\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 147 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operator: = (assignment or pattern matching)\n"); layoutBuilder->addLexem(std::string(yytext)); return '=';}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 148 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operator: : (cons)\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 149 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operator: ++ (list concatenation)\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 150 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operator: range (..)\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 151 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operator: . (function composition)\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 152 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operator: -> (function type)\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 153 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operator: <- (monad binding)\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 154 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operator: | (guards)\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 155 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operator: !! (list indexing)\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 156 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operator: \\ (lambda)\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 157 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operator: % (modulus)\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 158 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operator: ^ (exponentiation)\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 159 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operator: $ (function application)\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 160 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operator: type annotation (::)\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 161 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operator: as-pattern (@)\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 162 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operator: lazy pattern matching (~)\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 163 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found operator: type constraint (=>)\n"); layoutBuilder->addLexem(std::string(yytext));}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 165 "flex_bison/resources/haskell.flex"
{ 
	layoutBuilder->addLexem(std::string(yytext)); 
	if (layoutBuilder->canEmit()) {
		yyless(0);
		EMIT_LEXEM
	} 
	else {
		LOG_LEXEM("found function identifier: %s\n", yytext); 
		return FUNC_ID;
	}
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 176 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found constructor identifier: %s\n", yytext); layoutBuilder->addLexem(std::string(yytext)); return CONSTRUCT_ID; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 178 "flex_bison/resources/haskell.flex"
{ 
  	std::string cleaned;
  	if (!clean_integer(yytext, cleaned, 8)) {
		std::cerr << "Error! Incorrect octal literal: " << yytext << std::endl;
		return -1;
    }

	std::string after_literal;
	// записать в after_literal последовательность непробельных символов после сматченного числового литерала
	LOOKAHEAD(after_literal);
	
	if (after_literal.length() > 0 || std::none_of(after_literal.begin(), after_literal.end(), 
												   [](char c) {return c == '8' || c == '9' || std::isalpha(c); })) {
		long var = strtol(cleaned.c_str(), NULL, 8);
		LOG_LEXEM("found octal integer literal: %ld\n", var);
		if (after_literal.length() > 0) {
			UNPUT_STR(after_literal);
		}
	}
	else {
		std::cerr << "Error! Incorrect octal integer literal: " << cleaned + after_literal << std::endl;
		return -1;
	}
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 203 "flex_bison/resources/haskell.flex"
{
	std::string cleaned;
  	if (!clean_integer(yytext, cleaned, 10)) {
		std::cerr << "Error! Incorrect decimal literal: " << yytext << std::endl;
		return -1;
    }

	std::string after_literal;
	// записать в after_literal последовательность непробельных символов после сматченного числового литерала
	LOOKAHEAD(after_literal);
	
	if (after_literal.length() > 0 || std::none_of(after_literal.begin(), after_literal.end(), 
												   [](char c) {return std::isalpha(c); })) {
		long var = strtol(cleaned.c_str(), NULL, 0); 
		LOG_LEXEM("found decimal integer literal: %ld\n", var);
		if (after_literal.length() > 0) {
			UNPUT_STR(after_literal);
		}
		return INTC;
	}

	std::cerr << "Error! Incorrect decimal integer literal: " << cleaned + after_literal << std::endl;
	return -1;
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 228 "flex_bison/resources/haskell.flex"
{ 
	std::string cleaned;
  	if (!clean_integer(yytext, cleaned, 16)) {
		std::cerr << "Error! Incorrect hexadecimal integer literal: " << yytext << std::endl;
		return -1;
    }

	std::string after_literal;
	// записать в after_literal последовательность непробельных символов после сматченного числового литерала
	LOOKAHEAD(after_literal);
	
	if (after_literal.length() > 0 || std::none_of(after_literal.begin(), after_literal.end(), 
												   [](char c) {return std::isalpha(c); })) {
		long var = strtol(cleaned.c_str(), NULL, 16); 
		LOG_LEXEM("found hexadecimal integer literal: %ld\n", var);
		if (after_literal.length() > 0) {
			UNPUT_STR(after_literal);
		}
	}
	else {
		std::cerr << "Error! Incorrect hexadecimal integer literal: " << cleaned + after_literal << std::endl;
		return -1;
	}	
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 253 "flex_bison/resources/haskell.flex"
{ var_float = std::stold(replaceComma(yytext)); LOG_LEXEM("found float literal: %Lf\n", var_float); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 255 "flex_bison/resources/haskell.flex"
{ BEGIN(SINGLE_LINE_COMMENT); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 256 "flex_bison/resources/haskell.flex"

	YY_BREAK
case 72:
/* rule 72 can match eol */
YY_RULE_SETUP
#line 257 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("found a single line comment\n"); BEGIN(INITIAL); yyless(0); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 259 "flex_bison/resources/haskell.flex"
{ BEGIN(MULTI_LINE_COMMENT); opened_line = yylineno; }
	YY_BREAK
case 74:
/* rule 74 can match eol */
YY_RULE_SETUP
#line 260 "flex_bison/resources/haskell.flex"

	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 261 "flex_bison/resources/haskell.flex"

	YY_BREAK
case 76:
YY_RULE_SETUP
#line 262 "flex_bison/resources/haskell.flex"
{ BEGIN(INITIAL); LOG_LEXEM("found a multi line comment\n"); }
	YY_BREAK
case YY_STATE_EOF(MULTI_LINE_COMMENT):
#line 263 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("ERROR: end of file before end of comment opened in %d line", opened_line); return -1; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 265 "flex_bison/resources/haskell.flex"
{ BEGIN(CHAR); buffer = ""; opened_line = yylineno; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 266 "flex_bison/resources/haskell.flex"
{ buffer += "\a"; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 267 "flex_bison/resources/haskell.flex"
{ buffer += "\b"; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 268 "flex_bison/resources/haskell.flex"
{ buffer += "\f"; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 269 "flex_bison/resources/haskell.flex"
{ buffer += "\n"; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 270 "flex_bison/resources/haskell.flex"
{ buffer +=	"\r"; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 271 "flex_bison/resources/haskell.flex"
{ buffer += "\v"; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 272 "flex_bison/resources/haskell.flex"
{ buffer += "\t"; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 273 "flex_bison/resources/haskell.flex"
{ buffer += (char) strtol(yytext + 1, NULL, 0); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 274 "flex_bison/resources/haskell.flex"
{ buffer += "\\"; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 275 "flex_bison/resources/haskell.flex"
{ }
	YY_BREAK
case 88:
/* rule 88 can match eol */
YY_RULE_SETUP
#line 276 "flex_bison/resources/haskell.flex"
{ buffer += yytext; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 277 "flex_bison/resources/haskell.flex"
{ 
	BEGIN(INITIAL);
	if (buffer.size() > 1) {
		LOG_LEXEM("ERROR: char literal opened in %d line can't be longer than 1 symbol!\n", opened_line);
	}
	else {
		LOG_LEXEM("found char: %s\n", buffer.c_str());
	}
}
	YY_BREAK
case YY_STATE_EOF(CHAR):
#line 286 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("ERROR: end of file in char literal opened in %d line\n", opened_line); return -1; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 288 "flex_bison/resources/haskell.flex"
{ BEGIN(STRING); buffer = ""; opened_line = yylineno; }
	YY_BREAK
case 91:
/* rule 91 can match eol */
YY_RULE_SETUP
#line 289 "flex_bison/resources/haskell.flex"
{ yylineno += occurencesCount(yytext, "\n"); /* Multiline string separator */ }
	YY_BREAK
case 92:
/* rule 92 can match eol */
YY_RULE_SETUP
#line 290 "flex_bison/resources/haskell.flex"
{ buffer += yytext; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 291 "flex_bison/resources/haskell.flex"
{ BEGIN(INITIAL); LOG_LEXEM("found string: %s\n", buffer.c_str()); }
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 292 "flex_bison/resources/haskell.flex"
{ LOG_LEXEM("ERROR: end of file in string literal opened in %d line\n", opened_line); return -1; }
	YY_BREAK
case 94:
/* rule 94 can match eol */
YY_RULE_SETUP
#line 294 "flex_bison/resources/haskell.flex"
{ if (yytext[0] == '\n') { yylineno++; } layoutBuilder->addSpace(yytext[0]); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SINGLE_LINE_COMMENT):
#line 296 "flex_bison/resources/haskell.flex"
{ 
	layoutBuilder->eof();  
	if(!layoutBuilder->canEmit()) {
		return 0;
	}
	else {
		EMIT_LEXEM;
	}
}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 306 "flex_bison/resources/haskell.flex"
ECHO;
	YY_BREAK
#line 1439 "flex_bison/src/haskell.flex.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin.rdbuf();
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* The contents of this function are C++ specific, so the () macro is not used.
 * This constructor simply maintains backward compatibility.
 * DEPRECATED
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout ):
	yyin(arg_yyin ? arg_yyin->rdbuf() : std::cin.rdbuf()),
	yyout(arg_yyout ? arg_yyout->rdbuf() : std::cout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream& arg_yyin, std::ostream& arg_yyout ):
	yyin(arg_yyin.rdbuf()),
	yyout(arg_yyout.rdbuf())
{
	ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::ctor_common()
{
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = NULL;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree( yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree( yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream& new_in, std::ostream& new_out )
{
	// was if( new_in )
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );

	// was if( new_out )
	yyout.rdbuf(new_out.rdbuf());
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if( ! new_in ) {
		new_in = &yyin;
	}

	if ( ! new_out ) {
		new_out = &yyout;
	}

	switch_streams(*new_in, *new_out);
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin.eof() || yyin.fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin.get( buf[0] );

	if ( yyin.eof() )
		return 0;

	if ( yyin.bad() )
		return -1;

	return 1;

#else
	(void) yyin.read( buf, max_size );

	if ( yyin.bad() )
		return -1;
	else
		return yyin.gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout.write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    yy_state_type yyFlexLexer::yy_get_previous_state()
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 225 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 225 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 224);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
    void yyFlexLexer::yyunput( int c, char* yy_bp)
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}
#endif

    int yyFlexLexer::yyinput()
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyFlexLexer::yyrestart( std::istream& input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Delegate to the new version that takes an istream reference.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyFlexLexer::yyrestart( std::istream* input_file )
{
	if( ! input_file ) {
		input_file = &yyin;
	}
	yyrestart( *input_file );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

    void yyFlexLexer::yy_load_buffer_state()
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin.rdbuf(YY_CURRENT_BUFFER_LVALUE->yy_input_file);
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream& file, int size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Delegate creation of buffers to the new version that takes an istream reference.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
	YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	return yy_create_buffer( *file, size );
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream& file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file.rdbuf();
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 0;
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yyFlexLexer::yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
void yyFlexLexer::yyensure_buffer_stack(void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

    void yyFlexLexer::yy_push_state( int _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    void yyFlexLexer::yy_pop_state()
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    int yyFlexLexer::yy_top_state()
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError( const char* msg )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 306 "flex_bison/resources/haskell.flex"


static bool check_prefix(const std::string& input_string, int base) {
	int len = input_string.length();
	if (base == 8) {
		if (len < 3 || !(input_string[0] == '0' && (input_string[1] == 'o' || input_string[1] == 'O'))) {
			std::cerr << "Error: invalid prefix for octal number\n";
			return false;
		}
	} else if (base == 16) {
		if (len < 3 || !(input_string[0] == '0' && (input_string[1] == 'x' || input_string[1] == 'X'))) {
			std::cerr << "Error: invalid prefix for hexadecimal number\n";
			return false;
		}
	}
	return true; // Префикс корректен
}

static int clean_integer(const std::string& input_string, std::string& cleaned, int base) {
	int len = input_string.length();
	bool has_valid_digits = false;

	// Проверка на подчеркивания в начале и конце
	if (input_string.front() == '_' || input_string.back() == '_') {
		std::cerr << "Error: underscores cannot be at the beginning or end of the number\n";
		return 0;
	}

	// Проверка на префиксы для восьмеричных и шестнадцатеричных чисел
	if (!check_prefix(input_string, base)) {
		return 0;
	}

	// Пропускаем префикс для восьмеричных и шестнадцатеричных чисел
	int start_idx = (base == 10) ? 0 : 2;

	// Обрабатываем символы числа после префикса
	for (int i = start_idx; i < len; i++) {
		if (input_string[i] == '_') {
			// Пропускаем подчеркивания
			continue;
		}

		// Добавляем валидный символ в cleaned
		cleaned += input_string[i];
		has_valid_digits = true;
	}

	// Проверка, остались ли валидные цифры после удаления подчеркиваний
	if (!has_valid_digits) {
		std::cerr << "Error: no valid digits left after removing underscores\n";
		return 0;
	}

	return 1; 
}

std::string replaceComma(const std::string& str) {
	// TODO: разобраться почему возникает проблема с определением локали
	/* 
	#if defined(_WIN32) || defined(_WIN64)
		std::locale currentLocale("en-US");  // Windows
	#elif defined(__linux__) || defined(__unix__) || defined(__APPLE__)
		std::locale currentLocale("en_US.UTF-8");  // Linux/macOS
	#else
		std::locale currentLocale("");  // Используем локаль по умолчанию
	#endif
    // Получаем разделитель целой и дробной части в текущей локали
    const std::numpunct<char>& numPunct = std::use_facet<std::numpunct<char>>(currentLocale);

	// Не меняем строку если в текущий локали разделителем уже является . (как в хаскелле)
	if (numPunct.decimal_point() == '.') {
		return str;
	}
	*/

	std::string result = str;
	size_t start_pos = 0;

	while ((start_pos = result.find('.', start_pos)) != std::string::npos) {
		result.replace(start_pos, 1, ","); 
		start_pos++;  
	}

	return result; 
}

unsigned occurencesCount(std::string str, std::string substr) {
	unsigned occurences = 0;
	size_t pos = 0;

	while ((pos = str.find(substr, pos)) != std::string::npos) {
		pos += substr.length();
		occurences++;
	}

	return occurences;
}


